import 'package:flutter/material.dart';

class Character {
  final String name;
  final String fullName;
  final int age;
  final String imagePath;
  final String birthday;
  final String description;
  final Color color;
  final String zodiacSign;
  final String residence;
  final String occupation;
  Character(
      this.name,
      this.fullName,
      this.age,
      this.birthday,
      this.zodiacSign,
      this.residence,
      this.occupation,
      this.imagePath,
      this.description,
      this.color);

  static List<Character> fetchData() {
    return [
      Character(
          'Eren',
          'Eren Yeager',
          19,
          'March 30th',
          'Aries',
          'Wall Rose',
          'Former Soldier',
          'assets/images/eren.png',
          'Eren Yeager is the main protagonist of Attack on Titan. He lived in Shiganshina District with his parents until the fall of Wall Maria, where he impotently witnessed his mother being eaten by a Titan. This event would lead to Eren\'s intense hatred towards the Titans as he swore to wipe all of them off the face of the Earth.',
          Colors.deepPurpleAccent),
      Character(
          'Mikasa',
          'Mikasa Ackerman',
          19,
          'February 10th',
          'Aquarius',
          'Wall Rose',
          'Soldier',
          './assets/images/mikasa.png',
          'Mikasa Ackerman is one of the two deuteragonists of the series. After her parents were murdered by human traffickers, Mikasa was rescued by Eren Yeager and lived with him and his parents, Grisha and Carla, before the fall of Wall Maria. She is the last descendant of the Shogun clan that stayed on Paradis Island, thereby related to the Azumabito family, and holds significant political power in Hizuru.',
          Colors.pinkAccent),
      Character(
          'Armin',
          'Armin Arlert',
          19,
          'November 3rd',
          'Scorpio',
          'Wall Rose',
          'Soldier',
          './assets/images/armin.png',
          'Armin Arlelt is a soldier in the Scout Regiment. He is also a childhood friend of Eren Jaeger and Mikasa Ackermann, and is one of the two deuteragonists of the series. Although he appears to be the physically weakest of the 104th Cadet Corps, his high intelligence and strategic genius makes him an invaluable asset, though he does not consider himself to be one and is known to have low self-esteem.',
          Colors.greenAccent),
      Character(
          'Annie',
          'Annie Leonhart',
          23,
          'March 22nd',
          'Aries',
          'Wall Sheena',
          'Warrior',
          './assets/images/annie.png',
          'Annie Leonhart is a graduate of the 104th Training Corps and former member of the Military Police Brigade. Her exceptional skills with swords and unarmed combat earned her the 4th rank, but she is also noted to be a lone wolf who struggles to work with others.',
          Colors.yellowAccent),
      Character(
          'Reiner',
          'Reiner Braun',
          21,
          'August 1st',
          'Leo',
          'Liberio',
          'Warrior',
          './assets/images/reiner.png',
          'Reiner Braun is the Eldian Vice Chief of the Warriors and the main protagonist of Attack on Titan from the Marleyan perspective. He is the illegitimate son of an Eldian mother and a Marleyan father who grew up in Liberio\'s internment zone. Eventually, he was selected as a child to become one of Marley\'s Warriors. From a young age, he inherited the power of the Armored Titan.',
          Colors.amberAccent),
      Character(
          'Bertholdt',
          'Bertholdt Hoover',
          17,
          'December 30th',
          'Capricorn',
          'Unknown',
          'Warrior',
          './assets/images/bertholdt.png',
          'Bertolt Hoover was an Eldian and one of Marley\'s Warriors. He possessed the ability to transform into a Titan known as the Colossus Titan. In the year 845, he, Reiner Braun, and Annie Leonhart breached Wall Maria in an attempt to lure out and acquire the Founding Titan for Marley. After that, he joined the military and graduated the 104th Training Corps, ranked 3rd, and later joined the Survey Corps, until his identity as the Colossus Titan was revealed. He was described by others to be a weak-willed and quiet person.',
          Colors.lightGreenAccent),
      Character(
          'Erwin',
          'Erwin Smith',
          35,
          'October 14th',
          'Libra',
          'Wall Rose',
          'Soldier',
          './assets/images/erwin.png',
          'Erwin Smith was the 13th commander  of the Scout Regiment. Discerning, intelligent, and widely respected, Erwin was an able commander. While he cared deeply for his men, he did not hesitate to sacrifice them for the good and prosperity of mankind, and his men have proven more than willing to stake their lives at his order. Erwin developed the Long-Distance Enemy Scouting Formation. Due to uncertainty about his future, he later named Hange Zoë as his successor.',
          Colors.lightBlueAccent),
      Character(
          'Levi',
          'Levi Ackerman',
          30,
          'December 25th',
          'Capricorn',
          'Wall Rose',
          'Soldier',
          './assets/images/levi.png',
          'Levi Ackerman, often formally referred to as Captain Levi, is the squad captain of the Special Operations Squad within the Survey Corps and is widely known as humanity\'s strongest soldier.',
          Colors.deepOrangeAccent),
      Character(
          'Hange',
          'Hange Zoë',
          29,
          'September 5th',
          'Virgo',
          'Wall Rose',
          'Soldier',
          './assets/images/hange.png',
          'Hange Zoë was the 14th commander of the Survey Corps, named so by Erwin Smith before his death. Hange was formerly a squad leader in charge of the Fourth Squad, having the duties of innovative inventing and conducting research on Titans, including Eren Yeager. After being promoted to commander, Hange was also in charge of expedition planning, management of the regiment, recruiting, and all the other responsibilities previously handled by Erwin. Upon their death, they were succeeded by Armin Arlert.',
          const Color(0xFF580615)),
      Character(
          'Sasha',
          'Sasha Braus',
          20,
          'July 26th',
          'Leo',
          'Wall Rose',
          'Soldier',
          './assets/images/sasha.png',
          'Sasha Braus is a member of the Scout Regiment and one of the few former members of the 104th Cadet Corps, of which she is ranked 9th out of the top 10. A compulsive food hoarder with an overly polite way of speech, Sasha originated from Dauper, a village in the southern territory of Wall Rose.',
          const Color(0xffa40b27)),
      Character(
          'Jean',
          'Jean Kirstein',
          23,
          'April 7th',
          'Aries',
          'Wall Rose',
          'Soldier',
          './assets/images/jean.png',
          'Jean Kirschtein is a graduate of the 104th Cadet Corps, among whom he ranked the 6th best. Jean hails from Wall Rose\'s Trost District, and joined the military with hopes of living a peaceful life within the walls as part of the Military Police Regiment, but would later find himself joining the Scout Regiment.',
          const Color(0xFFA19D7B)),
      Character(
          'Connie',
          'Connie Springer',
          19,
          'May 2nd',
          'Taurus',
          'Wall Rose',
          'Soldier',
          './assets/images/connie.png',
          'Connie used to be one of the shorter members of the Survey Corps, standing two centimeters shorter than Levi Ackerman. He has a slim build, with gray eyes, and his brown hair is distinctively kept shaved. Connie is typically dressed in standard military garb, and will don the Survey Corps cape when on missions.',
          Colors.blueGrey.shade500),
      Character(
          'Ymir',
          'Ymir Lady',
          75,
          'February 17th',
          'Aquarius',
          'Unknown',
          'Former Soldier',
          './assets/images/ymir.png',
          'Ymir was a graduate of the 104th Training Corps and a former member of the Survey Corps. She also had the ability to transform into the Jaw Titan, and had knowledge about the true nature of Titans and the history of the world outside the Walls.',
          Colors.brown),
      Character(
          'Historia',
          'Historia Reiss',
          19,
          'January 15th',
          'Capricorn',
          'Mitras',
          'Queen',
          './assets/images/historia.png',
          'Historia Reiss is the current Queen of the Walls. She is also the illegitimate child of the nobleman Rod Reiss and is the last remaining member of the Reiss royal family. She was raised in isolation on one of the Reiss family estates until the fall of Wall Maria.',
          Colors.yellowAccent.shade700),
    ];
  }
}
